format = """
$env_var\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$python\
$nodejs\
$cmd_duration\
$jobs\
$time\
$line_break\
$character
"""


# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white) '
variable = "STARSHIP_DISTRO"
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold magenta"
home_symbol = " ~"
read_only = " "
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false

[fill]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_metrics]
disabled = true

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked\]]($style) )'
# format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[memory_usage]
symbol = " "

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = " [$time]($style)"
